-- Companion notify + offline queue + two-way sync (VOYN-W0-F5).
--
-- Acceptance: "state transitions доставляются при восстановлении сети" — a
-- companion that was offline while the backlog moved must learn every
-- transition it missed once the network returns.
--
-- Reuse first, because the expensive half is already built. `backlog_event`
-- (0005) is an append-only log of every state change, and `_backlog_audit` is
-- PERFORMed *inside* `backlog_transition`/`backlog_triage`/
-- `backlog_ingest_results` — so the log row and the status change commit or
-- roll back together. That transactional coupling is the whole difficulty of
-- an outbox, and this schema does not rebuild it: there is no second
-- transition log here. What was missing is everything on the delivery side —
-- nobody was a subscriber, nothing tracked what a given device had already
-- seen, and an event was therefore "delivered" only in the sense that it had
-- been written down.
--
-- Fan-out, not a cursor. The obvious design is one `last_seen_event_id` per
-- device and `WHERE event_id > cursor`, and it silently loses events:
-- `backlog_event.event_id` comes from an IDENTITY sequence, values are
-- allocated *before* commit, so a reader can observe event 10 while event 9 is
-- still in flight. Advance the cursor to 10 and event 9 — a real transition —
-- becomes unreachable the moment it commits. That failure needs concurrency to
-- reproduce, which means it would not show up until production. So delivery is
-- a row per (device, event), inserted by trigger in the producing transaction:
-- a row that has not committed yet is not visible, and when it does commit it
-- is simply a pending row like any other. Nothing to skip past, nothing to
-- reconstruct.
--
-- Push is a hint; the queue is the authority. `sync_record_push_attempt` never
-- marks anything delivered — only the client's own `sync_ack` does. A silently
-- dropped APNs/FCM notification therefore costs a delay until the next poll,
-- never a lost transition, and no notification vendor's reliability becomes
-- this system's reliability.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

-- A paired companion. `device_id` is chosen by the client (a UUID it keeps in
-- its keychain), which is what lets a reinstall re-register as itself instead
-- of orphaning its pending queue.
CREATE TABLE sync_device (
    device_id      text PRIMARY KEY,
    label          text        NOT NULL,
    platform       text        NOT NULL,
    push_transport text,
    push_token     text,
    registered_at  timestamptz NOT NULL DEFAULT now(),
    last_seen_at   timestamptz,
    revoked_at     timestamptz,
    CONSTRAINT sync_device_label_present CHECK (length(label) > 0),
    CONSTRAINT sync_device_platform_vocabulary
        CHECK (platform IN ('ios', 'android', 'desktop', 'test')),
    -- A token without the transport that can redeem it is undeliverable data
    -- that still looks like a reachable device; a transport without a token is
    -- a device that will be pushed to and never arrive.
    CONSTRAINT sync_device_push_pairing CHECK (
        (push_token IS NULL AND push_transport IS NULL)
        OR (push_token IS NOT NULL AND push_transport IS NOT NULL)
    )
);

-- The offline queue: one row per (device, notifiable event), created in the
-- transaction that created the event. `pending` means "this device has not
-- said it has this yet" — not "nobody tried", which is what `attempts`
-- records separately.
CREATE TABLE sync_delivery (
    delivery_id     bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    device_id       text        NOT NULL REFERENCES sync_device(device_id) ON DELETE CASCADE,
    event_id        bigint      NOT NULL REFERENCES backlog_event(event_id) ON DELETE CASCADE,
    state           text        NOT NULL DEFAULT 'pending',
    attempts        integer     NOT NULL DEFAULT 0,
    last_attempt_at timestamptz,
    last_error      text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    acked_at        timestamptz,
    CONSTRAINT sync_delivery_state_vocabulary CHECK (state IN ('pending', 'acked')),
    -- Re-running a fan-out (a replayed event, a re-registered device) must not
    -- notify twice.
    CONSTRAINT sync_delivery_once_per_device UNIQUE (device_id, event_id)
);

-- Partial: the queue drain only ever asks for pending rows, and the acked
-- history is the part that grows without bound.
CREATE INDEX idx_sync_delivery_pending
    ON sync_delivery (device_id, delivery_id) WHERE state = 'pending';

-- The upstream half of two-way sync. `command_id` is generated by the client
-- *when it composes the command offline*, not when it manages to send it,
-- which is what makes a retry after an ambiguous network failure idempotent:
-- the second attempt collides with this primary key and is answered from the
-- recorded outcome instead of being applied again.
CREATE TABLE sync_command (
    command_id  text PRIMARY KEY,
    device_id   text        NOT NULL REFERENCES sync_device(device_id) ON DELETE CASCADE,
    kind        text        NOT NULL,
    task_id     text,
    payload     jsonb       NOT NULL DEFAULT '{}'::jsonb,
    outcome     text        NOT NULL,
    reason      text,
    revision    bigint,
    received_at timestamptz NOT NULL DEFAULT now(),
    settled_at  timestamptz,
    CONSTRAINT sync_command_kind_vocabulary
        CHECK (kind IN ('transition', 'triage', 'evidence')),
    -- `in_flight` is transient and unobservable from another session: a
    -- concurrent submission of the same command_id blocks on the primary key
    -- until this transaction settles the row. It exists so the claim can be
    -- taken before the backlog function runs, rather than after.
    CONSTRAINT sync_command_outcome_vocabulary
        CHECK (outcome IN ('in_flight', 'applied', 'conflict', 'rejected'))
);

CREATE INDEX idx_sync_command_device ON sync_command (device_id, received_at DESC);

-- ---------------------------------------------------------------------------
-- Fan-out
-- ---------------------------------------------------------------------------

-- Which audit rows are worth a phone buzzing. `backlog_event` records the
-- whole protocol — including `lease_heartbeat`, which fires on a timer — so
-- forwarding it wholesale would train the operator to ignore the feed, which
-- is the same outcome as not sending it. Refusals are excluded for a different
-- reason: a rejected transition did not change the task, so there is no new
-- state to sync. They stay in `backlog_event`, where an operator debugging the
-- planner can still see them.
CREATE FUNCTION _sync_is_notifiable(p_event text, p_outcome text, p_task_id text)
    RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
    SELECT p_task_id IS NOT NULL
       AND p_outcome = 'granted'
       AND p_event IN ('transition', 'triage', 'ingest');
$$;

CREATE FUNCTION _sync_fan_out() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
BEGIN
    IF NOT _sync_is_notifiable(NEW.event, NEW.outcome, NEW.task_id) THEN
        RETURN NULL;
    END IF;
    -- Revoked devices are skipped here rather than filtered at read time: a
    -- retired phone must stop accruing a queue, not accrue one nobody drains.
    INSERT INTO sync_delivery (device_id, event_id)
    SELECT d.device_id, NEW.event_id
      FROM sync_device d
     WHERE d.revoked_at IS NULL
    ON CONFLICT (device_id, event_id) DO NOTHING;
    RETURN NULL;
END
$$;

-- AFTER INSERT, so a failure to enqueue a notification aborts the transition
-- that produced it rather than committing a state change nobody will hear
-- about. That is the correct direction for this system: the backlog is the
-- thing being reported on, and a report nobody receives is the failure F5
-- exists to prevent.
CREATE TRIGGER sync_fan_out_on_backlog_event
    AFTER INSERT ON backlog_event
    FOR EACH ROW EXECUTE FUNCTION _sync_fan_out();

-- ---------------------------------------------------------------------------
-- Protocol
-- ---------------------------------------------------------------------------

CREATE TYPE sync_verdict AS (
    ok     boolean,
    reason text
);

-- Register, or rotate a push token for an already-known device. Re-registering
-- is the normal case, not an error: APNs and FCM rotate tokens on reinstall and
-- on OS whim, and treating that as a new device would strand the old device's
-- pending queue.
--
-- A revoked device is refused rather than resurrected. Revocation is what an
-- operator does about a lost phone, so a device_id that can re-register itself
-- would make that act advisory.
CREATE FUNCTION sync_register_device(
    p_device_id      text,
    p_label          text,
    p_platform       text,
    p_push_transport text DEFAULT NULL,
    p_push_token     text DEFAULT NULL
) RETURNS sync_verdict
    LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE d sync_device%ROWTYPE; v sync_verdict;
BEGIN
    v.ok := false;
    IF p_device_id IS NULL OR length(btrim(p_device_id)) = 0 THEN
        v.reason := 'empty_device_id'; RETURN v;
    END IF;

    SELECT * INTO d FROM sync_device s WHERE s.device_id = p_device_id FOR UPDATE;
    IF FOUND AND d.revoked_at IS NOT NULL THEN
        v.reason := 'revoked'; RETURN v;
    END IF;

    BEGIN
        INSERT INTO sync_device (device_id, label, platform, push_transport, push_token)
        VALUES (p_device_id, p_label, p_platform, p_push_transport, p_push_token)
        ON CONFLICT (device_id) DO UPDATE
            SET label          = excluded.label,
                platform       = excluded.platform,
                push_transport = excluded.push_transport,
                push_token     = excluded.push_token;
    EXCEPTION WHEN check_violation THEN
        -- The CHECK vocabulary is the authority on what a device may look like;
        -- restating it here would create a second one that can disagree.
        v.reason := 'constraint: ' || SQLERRM; RETURN v;
    END;

    v.ok := true;
    v.reason := CASE WHEN d.device_id IS NULL THEN 'registered' ELSE 'updated' END;
    RETURN v;
END
$$;

-- Revoke a device. Its pending queue goes with it (ON DELETE CASCADE does not
-- apply — the rows are deleted explicitly) because an undeliverable queue for a
-- retired phone is storage that only ever grows.
CREATE FUNCTION sync_revoke_device(p_device_id text) RETURNS sync_verdict
    LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE d sync_device%ROWTYPE; v sync_verdict;
BEGIN
    v.ok := false;
    SELECT * INTO d FROM sync_device s WHERE s.device_id = p_device_id FOR UPDATE;
    IF NOT FOUND THEN
        v.reason := 'unknown_device'; RETURN v;
    END IF;
    IF d.revoked_at IS NOT NULL THEN
        -- Idempotent: revoking twice is what a retry looks like.
        v.ok := true; v.reason := 'already_revoked'; RETURN v;
    END IF;

    UPDATE sync_device s
       SET revoked_at = now(), push_token = NULL, push_transport = NULL
     WHERE s.device_id = p_device_id;
    DELETE FROM sync_delivery WHERE device_id = p_device_id AND state = 'pending';

    v.ok := true; v.reason := 'revoked';
    RETURN v;
END
$$;

-- The queue drain. Returns the device's undelivered transitions oldest-first,
-- joined to enough of the task to render a notification without a second round
-- trip on a link that may be about to disappear again.
--
-- `last_seen_at` is stamped here on purpose: a poll IS the device telling us it
-- is reachable, and that is what lets the push side distinguish "asleep, send a
-- notification" from "already draining, do not".
CREATE FUNCTION sync_fetch_pending(p_device_id text, p_limit integer DEFAULT 200)
    RETURNS TABLE (
        delivery_id  bigint,
        event_id     bigint,
        task_id      text,
        event        text,
        detail       jsonb,
        occurred_at  timestamptz,
        attempts     integer,
        task_title   text,
        task_status  text,
        task_revision bigint
    )
    LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE v_limit integer := least(greatest(coalesce(p_limit, 200), 1), 1000);
BEGIN
    UPDATE sync_device s SET last_seen_at = now()
     WHERE s.device_id = p_device_id AND s.revoked_at IS NULL;
    IF NOT FOUND THEN
        -- Unknown or revoked: an empty queue, not an exception. A revoked
        -- device polling on is a client that has not been told yet, and the
        -- HTTP layer turns the absent device into the 404 that tells it.
        RETURN;
    END IF;

    RETURN QUERY
    SELECT sd.delivery_id, sd.event_id, be.task_id, be.event, be.detail,
           be.created_at, sd.attempts, bt.title, bt.status, bt.revision
      FROM sync_delivery sd
      JOIN backlog_event be ON be.event_id = sd.event_id
      LEFT JOIN backlog_task bt ON bt.task_id = be.task_id
     WHERE sd.device_id = p_device_id
       AND sd.state = 'pending'
     ORDER BY sd.delivery_id
     LIMIT v_limit;
END
$$;

-- Acknowledge by explicit id, never by watermark.
--
-- A `through_delivery_id` high-water mark would reintroduce exactly the bug the
-- fan-out design avoids: ids are allocated before commit, so acking "everything
-- through 40" can cover a row numbered 37 that had not yet appeared when the
-- client built its list, and that row would be marked delivered to a device
-- that never saw it. An explicit list can only ever settle rows the client
-- actually holds.
CREATE FUNCTION sync_ack(p_device_id text, p_delivery_ids bigint[]) RETURNS integer
    LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE v_count integer;
BEGIN
    IF p_delivery_ids IS NULL OR cardinality(p_delivery_ids) = 0 THEN
        RETURN 0;
    END IF;
    WITH settled AS (
        UPDATE sync_delivery sd
           SET state = 'acked', acked_at = now()
         WHERE sd.device_id = p_device_id
           -- Scoped to the caller's own rows: a device may not settle another
           -- device's queue, so a wrong or hostile id list is a no-op rather
           -- than someone else's lost notification.
           AND sd.delivery_id = ANY (p_delivery_ids)
           AND sd.state = 'pending'
        RETURNING 1
    )
    SELECT count(*) INTO v_count FROM settled;
    UPDATE sync_device s SET last_seen_at = now() WHERE s.device_id = p_device_id;
    RETURN v_count;
END
$$;

-- Record that a push was attempted. Deliberately does NOT settle anything: push
-- is a hint that a queue is worth draining, and treating a successful handoff to
-- APNs as delivery would mark a notification delivered on the strength of a
-- third party accepting it for later. The counters are what a backoff schedule
-- reads, and what makes a device that is failing to receive visible.
CREATE FUNCTION sync_record_push_attempt(
    p_device_id text, p_delivery_ids bigint[], p_ok boolean, p_error text DEFAULT NULL
) RETURNS integer
    LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE v_count integer;
BEGIN
    IF p_delivery_ids IS NULL OR cardinality(p_delivery_ids) = 0 THEN
        RETURN 0;
    END IF;
    WITH touched AS (
        UPDATE sync_delivery sd
           SET attempts        = sd.attempts + 1,
               last_attempt_at = now(),
               last_error      = CASE WHEN p_ok THEN NULL ELSE p_error END
         WHERE sd.device_id = p_device_id
           AND sd.delivery_id = ANY (p_delivery_ids)
           AND sd.state = 'pending'
        RETURNING 1
    )
    SELECT count(*) INTO v_count FROM touched;
    RETURN v_count;
END
$$;

-- Apply one command from a device, exactly once.
--
-- Two properties an offline client cannot work without, both delegated rather
-- than reimplemented:
--
--   * **Idempotency** — the claim is taken by inserting `command_id` before the
--     backlog function runs. A duplicate collides on the primary key and is
--     answered from the recorded outcome. A concurrent duplicate blocks on that
--     key until the first settles, so it too reads a final answer, never a
--     partial one.
--   * **Conflict detection** — a command composed offline was composed against
--     a revision that may since have moved. `backlog_transition` already
--     refuses on `revision_conflict`; this surfaces that as its own outcome so
--     the client can rebase and resubmit instead of silently clobbering a
--     decision made while it was away.
--
-- The backlog functions remain the only authority on whether a move is legal.
-- Nothing here re-decides a status machine.
CREATE FUNCTION sync_submit_command(
    p_command_id text,
    p_device_id  text,
    p_kind       text,
    p_task_id    text,
    p_payload    jsonb DEFAULT '{}'::jsonb
) RETURNS TABLE (outcome text, reason text, revision bigint, duplicate boolean)
    LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE c sync_command%ROWTYPE; bv backlog_verdict; v_claimed boolean := false;
        v_payload jsonb := coalesce(p_payload, '{}'::jsonb);
        v_outcome text; v_reason text; v_revision bigint;
        v_expected bigint; v_to_status text;
BEGIN
    IF p_command_id IS NULL OR length(btrim(p_command_id)) = 0 THEN
        outcome := 'rejected'; reason := 'empty_command_id'; duplicate := false;
        RETURN NEXT; RETURN;
    END IF;

    PERFORM 1 FROM sync_device s
      WHERE s.device_id = p_device_id AND s.revoked_at IS NULL;
    IF NOT FOUND THEN
        outcome := 'rejected'; reason := 'unknown_or_revoked_device'; duplicate := false;
        RETURN NEXT; RETURN;
    END IF;

    -- Claim first, execute second. The reverse order applies the command and
    -- then discovers it was a duplicate.
    INSERT INTO sync_command (command_id, device_id, kind, task_id, payload, outcome)
    VALUES (p_command_id, p_device_id, p_kind, p_task_id, v_payload, 'in_flight')
    ON CONFLICT (command_id) DO NOTHING;
    GET DIAGNOSTICS v_claimed = ROW_COUNT;

    IF NOT v_claimed THEN
        SELECT * INTO c FROM sync_command sc WHERE sc.command_id = p_command_id;
        outcome := c.outcome; reason := c.reason; revision := c.revision;
        duplicate := true;
        RETURN NEXT; RETURN;
    END IF;

    IF p_kind = 'transition' THEN
        v_to_status := nullif(btrim(v_payload ->> 'to_status'), '');
        BEGIN
            v_expected := (v_payload ->> 'expected_revision')::bigint;
        EXCEPTION WHEN invalid_text_representation THEN
            v_expected := NULL;
        END;
        IF v_to_status IS NULL OR v_expected IS NULL THEN
            -- Optimistic concurrency is not optional on this path: without an
            -- expected revision an offline command would apply against whatever
            -- the task happens to be now, which is the clobber this exists to
            -- prevent.
            v_outcome := 'rejected';
            v_reason  := 'transition requires to_status and expected_revision';
        ELSE
            bv := backlog_transition(p_task_id, v_to_status, v_expected);
            v_revision := bv.revision;
            IF bv.ok THEN
                v_outcome := 'applied'; v_reason := 'transitioned';
            ELSIF bv.reason = 'revision_conflict' THEN
                v_outcome := 'conflict'; v_reason := bv.reason;
            ELSE
                v_outcome := 'rejected'; v_reason := bv.reason;
            END IF;
        END IF;

    ELSIF p_kind = 'triage' THEN
        bv := backlog_triage(p_task_id,
                             nullif(btrim(v_payload ->> 'decision'), ''),
                             nullif(btrim(v_payload ->> 'detail'), ''));
        v_revision := bv.revision;
        v_outcome := CASE WHEN bv.ok THEN 'applied' ELSE 'rejected' END;
        v_reason  := coalesce(bv.reason, 'triaged');

    ELSIF p_kind = 'evidence' THEN
        bv := backlog_record_evidence(p_task_id,
                                      nullif(btrim(v_payload ->> 'kind'), ''),
                                      nullif(btrim(v_payload ->> 'value'), ''));
        v_revision := bv.revision;
        v_outcome := CASE WHEN bv.ok THEN 'applied' ELSE 'rejected' END;
        v_reason  := coalesce(bv.reason, 'recorded');

    ELSE
        v_outcome := 'rejected';
        v_reason  := 'unknown_kind: ' || coalesce(p_kind, '?');
    END IF;

    UPDATE sync_command sc
       SET outcome = v_outcome, reason = v_reason, revision = v_revision,
           settled_at = now()
     WHERE sc.command_id = p_command_id;

    outcome := v_outcome; reason := v_reason; revision := v_revision;
    duplicate := false;
    RETURN NEXT;
END
$$;
