"""Accessibility repairs for semantics generated by Streamlit's app shell.

Streamlit owns the outer document, so Python widgets cannot set these
attributes directly. A static inline script keeps the repair attached across
incremental renders and reruns without changing visible content.
"""

from __future__ import annotations

import streamlit as st


_SHELL_REPAIR = """
<script>
(() => {
  const document = window.parent.document;

  const repair = () => {
    const main = document.querySelector("section[data-testid='stMain']");
    if (main) main.removeAttribute("tabindex");

    const sidebar = document.querySelector("section[data-testid='stSidebar']");
    if (sidebar) {
      sidebar.removeAttribute("aria-expanded");
      sidebar.setAttribute("role", "navigation");
      sidebar.setAttribute("aria-label", "Основная навигация");
    }

    document.querySelectorAll("h1 a, h2 a, h3 a, h4 a, h5 a, h6 a")
      .forEach((anchor) => {
        anchor.setAttribute("aria-hidden", "true");
        anchor.setAttribute("tabindex", "-1");
      });

    const iconLabels = {
      keyboard_double_arrow_left: "Скрыть навигацию",
      keyboard_double_arrow_right: "Показать навигацию",
      menu: "Открыть навигацию",
      close: "Закрыть",
    };
    document.querySelectorAll("button [data-testid='stIconMaterial']")
      .forEach((icon) => {
        const button = icon.closest("button");
        if (button && !(button.getAttribute("aria-label") || "").trim()) {
          const label = iconLabels[icon.textContent.trim()];
          if (label) button.setAttribute("aria-label", label);
        }
        icon.setAttribute("aria-hidden", "true");
      });
  };

  repair();
  new MutationObserver(repair).observe(document.body, {
    childList: true,
    subtree: true,
  });
})();
</script>
"""


def repair_streamlit_shell_semantics() -> None:
    """Remove non-content tab stops and decorative accessible names."""
    st.html(_SHELL_REPAIR, unsafe_allow_javascript=True)
